-- MySQL Script generated by MySQL Workbench
-- qua 08 mai 2024 19:02:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbPj3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbPj3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbPj3` ;
USE `dbPj3` ;

-- -----------------------------------------------------
-- Table `dbPj3`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPj3`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NULL,
  `senha` VARCHAR(100) NULL DEFAULT '',
  `googleId` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `facebookId` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `apelido` VARCHAR(45) NULL,
  `nome` VARCHAR(50) NULL,
  `cidade` VARCHAR(50) NULL,
  `sexo` ENUM('F', 'M', 'O') NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPj3`.`visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPj3`.`visitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `dataDaVisita` DATETIME NOT NULL DEFAULT now(),
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_visitas_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_visitas_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `dbPj3`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPj3`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPj3`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `roles` ENUM('ADM', 'TOTEM') NOT NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPj3`.`catalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPj3`.`catalogo` (
  `uuid` VARCHAR(50) NOT NULL,
  `funcionario_autor` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `nomePopular` VARCHAR(45) NOT NULL,
  `nomeCientifico` VARCHAR(45) NOT NULL,
  `som` VARCHAR(45) NULL,
  `medalha` VARCHAR(45) NULL,
  `estrela` DECIMAL(1,1) NULL,
  `nascimento` DATE NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_arvore_funcionario1_idx` (`funcionario_autor` ASC) VISIBLE,
  UNIQUE INDEX `funcionario_autor_UNIQUE` (`funcionario_autor` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`uuid` ASC) VISIBLE,
  CONSTRAINT `fk_arvore_funcionario1`
    FOREIGN KEY (`funcionario_autor`)
    REFERENCES `dbPj3`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPj3`.`lidoPeloUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPj3`.`lidoPeloUser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `catalogo_uuid` VARCHAR(50) NOT NULL,
  `dataDaDescoberta` DATETIME NOT NULL DEFAULT now(),
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_descobertasInteressantes_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_lidoPeloUser_catalogo1_idx` (`catalogo_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_descobertasInteressantes_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `dbPj3`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lidoPeloUser_catalogo1`
    FOREIGN KEY (`catalogo_uuid`)
    REFERENCES `dbPj3`.`catalogo` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbPj3`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbPj3`.`foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `catalogo_uuid` VARCHAR(50) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_foto_catalogo1_idx` (`catalogo_uuid` ASC) VISIBLE,
  CONSTRAINT `fk_foto_catalogo1`
    FOREIGN KEY (`catalogo_uuid`)
    REFERENCES `dbPj3`.`catalogo` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
