-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 17:26:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NULL,
  `senhaHash` VARCHAR(100) NULL,
  `foto` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL,
  `senhaHash` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `adm` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `visitante_id` INT NOT NULL,
  `funcionario_id` INT NULL,
  `dataDaVisita` DATETIME NOT NULL,
  INDEX `fk_visitas_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `visitante_id`),
  CONSTRAINT `fk_visitas_visitante1`
    FOREIGN KEY (`visitante_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visitas_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pontoDeInteresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pontoDeInteresse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcionario_autor` INT NOT NULL,
  `foto_id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `nomePopular` VARCHAR(45) NULL,
  `nomeCientifico` VARCHAR(45) NULL,
  `som` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_arvore_funcionario1_idx` (`funcionario_autor` ASC) VISIBLE,
  INDEX `fk_pontoDeInteresse_foto1_idx` (`foto_id` ASC) VISIBLE,
  CONSTRAINT `fk_arvore_funcionario1`
    FOREIGN KEY (`funcionario_autor`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pontoDeInteresse_foto1`
    FOREIGN KEY (`foto_id`)
    REFERENCES `mydb`.`foto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`descobertasInteressantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`descobertasInteressantes` (
  `usuario_id` INT NOT NULL,
  `pontoDeInteresse_id` INT NOT NULL,
  `dataDaDescoberta` DATETIME NOT NULL,
  PRIMARY KEY (`usuario_id`, `pontoDeInteresse_id`),
  INDEX `fk_descobertasInteressantes_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_descobertasInteressantes_pontoDeInteresse1_idx` (`pontoDeInteresse_id` ASC) VISIBLE,
  CONSTRAINT `fk_descobertasInteressantes_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_descobertasInteressantes_pontoDeInteresse1`
    FOREIGN KEY (`pontoDeInteresse_id`)
    REFERENCES `mydb`.`pontoDeInteresse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
